import React from 'react';
import { MarketingSuggestionsProps } from '../types';
import { formatMarkdownText } from '../utils/helpers';

const MarketingSuggestions: React.FC<MarketingSuggestionsProps> = ({ suggestions }) => {
  const formattedSuggestions = formatMarkdownText(suggestions);

  return (
    <div className="bg-white/50 dark:bg-gray-800/50 backdrop-blur-lg p-8 rounded-2xl shadow-2xl border-2 border-amber-500/50 w-full max-w-2xl mt-8 animate-fade-in">
      <div className="flex items-center mb-4">
        <div className="w-8 h-8 bg-amber-500 rounded-full flex items-center justify-center mr-3">
          <svg className="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
          </svg>
        </div>
        <h3 className="text-2xl font-bold text-gray-900 dark:text-white">💡 Marketing Suggestions</h3>
      </div>
      
      <div className="prose dark:prose-invert max-w-none bg-gray-100/50 dark:bg-gray-900/50 p-6 rounded-lg border border-gray-200 dark:border-gray-700">
        <div className="space-y-2">
          {formattedSuggestions}
        </div>
      </div>
      
      <div className="mt-4 p-3 bg-amber-50 dark:bg-amber-900/20 rounded-lg border border-amber-200 dark:border-amber-700/50">
        <p className="text-sm text-amber-700 dark:text-amber-300 flex items-center">
          <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
          </svg>
          These creative marketing ideas were generated by AI to help promote your app.
        </p>
      </div>
    </div>
  );
};

export default MarketingSuggestions;