import React from 'react';
import { PitchAnalysisProps } from '../types';
import { formatMarkdownText } from '../utils/helpers';

const PitchAnalysis: React.FC<PitchAnalysisProps> = ({ analysis }) => {
  const formattedAnalysis = formatMarkdownText(analysis);

  return (
    <div className="bg-white/50 dark:bg-gray-800/50 backdrop-blur-lg p-8 rounded-2xl shadow-2xl border-2 border-teal-500/50 w-full max-w-2xl mt-8 animate-fade-in">
      <div className="flex items-center mb-4">
        <div className="w-8 h-8 bg-teal-500 rounded-full flex items-center justify-center mr-3">
          <svg className="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
          </svg>
        </div>
        <h3 className="text-2xl font-bold text-gray-900 dark:text-white">🔬 Pitch Analysis</h3>
      </div>
      
      <div className="prose dark:prose-invert max-w-none bg-gray-100/50 dark:bg-gray-900/50 p-6 rounded-lg border border-gray-200 dark:border-gray-700">
        <div className="space-y-2">
          {formattedAnalysis}
        </div>
      </div>
      
      <div className="mt-4 p-3 bg-teal-50 dark:bg-teal-900/20 rounded-lg border border-teal-200 dark:border-teal-700/50">
        <p className="text-sm text-teal-700 dark:text-teal-300 flex items-center">
          <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
          </svg>
          This analysis was generated by AI and provides suggestions to improve your pitch.
        </p>
      </div>
    </div>
  );
};

export default PitchAnalysis;